apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/name: sparkoperator
  kustomize.component: spark-operator
images:
- name: gcr.io/spark-operator/spark-operator
  newName: gcr.io/spark-operator/spark-operator
  newTag: v1beta2-1.1.0-2.4.5
kind: Kustomization
namePrefix: spark-operator
namespace: kubeflow
resources:
- spark-sa.yaml
- cluster-role.yaml
- crb.yaml
- deployment.yaml
- operator-sa.yaml
- role.yaml
- role-binding.yaml
- spark-apps-spark-operator-crd.yaml
- scheduled-spark-app-crd.yaml